// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`

Future<String> svgCircle() => RustLib.instance.api.crateApiFrontendSvgCircle();

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<FSegment>>
abstract class FSegment implements RustOpaqueInterface {
  Future<BigInt> id();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Frontend>>
abstract class Frontend implements RustOpaqueInterface {
  void changeParameter({required double eps});

  static Future<Frontend> create() =>
      RustLib.instance.api.crateApiFrontendFrontendCreate();

  Future<String> renderSegmentTrack({required FSegment segment});

  Future<String> renderSegmentWaypoints({required FSegment segment});

  Future<String> renderTrack();

  Future<String> renderWaypoints();

  Future<List<FSegment>> segments();
}
